substitutions:
  devicename: ventilatie
  upper_devicename: Ventilatie

esphome:
  name: ventilatie
  comment: Ventilatie aansturing

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_ventilatie
 
ota:
  - platform: esphome
    password: !secret ventilatie_ota_password


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none  
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.1.x
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.1.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0  

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ventilatie Fallback"
    password: !secret ventilatie_ap_password

captive_portal:

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: Europe/Amsterdam

# Load external components
# https://esphome.io/components/external_components.html#external-components-git
external_components:
  - source: github://Awakatanka/ESPHome-Zehnder-RF

# ---------- SPI (VSPI - VEILIG) ----------
spi:
  clk_pin: GPIO18   # CLK or SCK
  mosi_pin: GPIO23
  miso_pin: GPIO19
  #interface: hardware

# ---------- NRF905 ----------
nrf905:
  id: nrf905_rf
  cs_pin: GPIO17    #CS or CSN
  cd_pin: GPIO33   
  ce_pin: GPIO27
  pwr_pin: GPIO26
  txen_pin: GPIO25   #TX_EN
# ----------- Use the GND near 3V3 our GND near GPIO23/18 pins ----------
  # We don't need AM and DR at the moment as they are read from the inernal registers
  # am_pin: GPIO32
  # dr_pin: GPIO35
  
# ---------- ZEHNDER FAN ----------
fan:
  - platform: zehnder
    id: zehnder_fan
    name: "Ventilatie"
    nrf905: nrf905_rf
    update_interval: 60s   
    setup_priority: -100

# ------------ Button -------------
# ---- zehnder_fan->setSpeed(3, 10) 3=speed and 10 is time ------

button:
  - platform: restart
    id: ${devicename}_esphome_restart
    name: ${upper_devicename} herstart

  - platform: template
    id: ${devicename}_low
    name: ${upper_devicename} Low
    on_press:
      then:
        lambda: |-
          zehnder_fan->setSpeed(1, 0);
          
  - platform: template
    id: ${devicename}_medium
    name: ${upper_devicename} Medium
    on_press:
      then:
        lambda: |-
          zehnder_fan->setSpeed(2, 0);

  - platform: template
    id: ${devicename}_high
    name: ${upper_devicename} High
    on_press:
      then:
        lambda: |-
          zehnder_fan->setSpeed(3, 0);
  
  - platform: factory_reset
    id: ${devicename}_reset_pairing
    name: ${upper_devicename} Reset & Pair
